# Generated by Django 6.0.5 on 2026-05-16 16:38

import django.db.models.deletion
import unfold_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique configuration key used by the frontend.', max_length=255, unique=True, verbose_name='Key')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this setting controls.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='JSONValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='JSON Data')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='json_value', to='unfold_settings.setting')),
            ],
            options={
                'verbose_name': 'JSON Value',
                'verbose_name_plural': 'JSON Values',
            },
        ),
        migrations.CreateModel(
            name='HTMLValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='HTML Code')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='html_value', to='unfold_settings.setting')),
            ],
            options={
                'verbose_name': 'HTML Value',
                'verbose_name_plural': 'HTML Values',
            },
        ),
        migrations.CreateModel(
            name='FileValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(upload_to=unfold_settings.models.settings_upload_path, verbose_name='File')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_value', to='unfold_settings.setting')),
            ],
            options={
                'verbose_name': 'File Value',
                'verbose_name_plural': 'File Values',
            },
        ),
        migrations.CreateModel(
            name='DateValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='date_value', to='unfold_settings.setting')),
            ],
            options={
                'verbose_name': 'Date Value',
                'verbose_name_plural': 'Date Values',
            },
        ),
        migrations.CreateModel(
            name='DateTimeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(blank=True, null=True, verbose_name='Date and Time')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datetime_value', to='unfold_settings.setting')),
            ],
            options={
                'verbose_name': 'Date Time Value',
                'verbose_name_plural': 'Date Time Values',
            },
        ),
        migrations.CreateModel(
            name='BoolValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False, verbose_name='Enabled')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bool_value', to='unfold_settings.setting')),
            ],
            options={
                'verbose_name': 'Boolean Value',
                'verbose_name_plural': 'Boolean Values',
            },
        ),
        migrations.CreateModel(
            name='StringValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='Value')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='string_value', to='unfold_settings.setting')),
            ],
            options={
                'verbose_name': 'String Value',
                'verbose_name_plural': 'String Values',
            },
        ),
        migrations.CreateModel(
            name='TextValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, verbose_name='Value')),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_value', to='unfold_settings.setting')),
            ],
            options={
                'verbose_name': 'Text Value',
                'verbose_name_plural': 'Text Values',
            },
        ),
    ]
